name: CI-V2

on:
  push:
    branches: [ redesign ]
  pull_request:
    branches: [ redesign ]

env:
  DEPLOY_GENERAL_MICHAEL_PATH: /home/mix/ftennisi-release.ozma-split.com
  DEPLOY_GENERAL_ALEX_PATH: /home/develop/front
  BUILD_GENERAL_SCRIPT: npm run build:production
  BUILD_GENERAL_SCRIPT_OUTPUT: dist
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Делаем checkout текущей ветки
      - uses: actions/checkout@v2
      # Устанавливаем Node.JS для сборки приложения
      - uses: actions/setup-node@v1
        with:
          node-version: '16.13.0'
      # Записываем в переменные окружения имя текущей ветки
      # Чтобы избежать конфиликтов с URL, меняем точки на _, а слеши на минусы
      - name: Get branch name
        run: git checkout redesign
      # Устанавливаем зависимости для сборки
      - name: Install Dependencies
        run: npm i --legacy-peer-deps
      # Собираем приложение основное
      - name: Build App general
        run: $BUILD_GENERAL_SCRIPT
      # Доставляем основное собранное приложение на сервер
      - name: Deploy to Server Michael
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.YC_DEPLOY_SERVER_HOST }}
          port: ${{ secrets.YC_DEPLOY_SERVER_PORT }}
          username: ${{ secrets.YC_DEPLOY_SERVER_USERNAME }}
          password: ${{ secrets.YC_PASSWORD }}
          source: ${{ env.BUILD_GENERAL_SCRIPT_OUTPUT }}
          target: ${{ env.DEPLOY_GENERAL_MICHAEL_PATH }}/
          strip_components: 1
